#!/usr/bin/env bash

set -o pipefail

JAVA_CMD=${JAVA_CMD:=$(which java)}

if [ -z "$JAVA_CMD" ]; then
  echo "ERROR: Java is not installed."
  exit 1
fi

set -e

if [ -n "$JAVA_HOME" ]; then
	java_cmd="${JAVA_HOME}/bin/java"

	if [ -x "$java_cmd" ]; then
		JAVA_CMD="$java_cmd"
	else
		echo "$java_bin not executable or doesn't exist"
		exit 1
	fi
fi

# Resolve links - $0 may be a softlink
FORWARDER_BIN="$0"

while [ -h "$FORWARDER_BIN" ]; do
    ls=$(ls -ld "$FORWARDER_BIN")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        FORWARDER_BIN="$link"
    else
        FORWARDER_BIN=$(dirname "$FORWARDER_BIN")/"$link"
    fi
done

FORWARDER_ROOT="$(dirname $(dirname $FORWARDER_BIN))"
FORWARDER_DEFAULT_JAR="${FORWARDER_ROOT}/graylog-forwarder.jar"
FORWARDER_JVM_OPTIONS_FILE="${FORWARDER_JVM_OPTIONS_FILE:-$FORWARDER_ROOT/config/jvm.options}"

FORWARDER_PARSED_JAVA_OPTS=""
if [ -f "$FORWARDER_JVM_OPTIONS_FILE" ]; then
	FORWARDER_PARSED_JAVA_OPTS=$(grep '^-' "$FORWARDER_JVM_OPTIONS_FILE" | tr '\n' ' ')
fi

FORWARDER_JAVA_OPTS="${FORWARDER_PARSED_JAVA_OPTS% } $JAVA_OPTS"
FORWARDER_JAR=${FORWARDER_JAR:="$FORWARDER_DEFAULT_JAR"}

exec "$JAVA_CMD" ${FORWARDER_JAVA_OPTS% } -jar "$FORWARDER_JAR" "$@"
